# Manual steps after creating environment:
#  - switch to improve_estimation_table branch in estimagic source
#  - pip install -e ../relative/path/to/estimagic

name: estimagic_tables_examples
channels:
  - conda-forge
  - nodefaults

dependencies:
  - conda-lock
  - ipykernel
  - pandas
  - pdbpp
  - phantomjs
  - pip >=21.1
  - pre-commit
  - pytask-latex
  - pytask-parallel
  - pytask>=0.2
  - python-graphviz
  - python=3.10
  - pyyaml
  - setuptools_scm
  - statsmodels
  - toml
  - pip:
      - -e .
      - kaleido
